### ISSUE TITLE
HM3D preprocess

### ISSUE THREAD

**Issue by Hoyyyaard** [scene-verse/SceneVerse#10] opened 2024-06-17 02:56 UTC
Thank you for your impressive work! Could you please provide the script for processing HM3D scenes, or alternatively, the specific steps for processing them? Thank you very much.

**Comment by Hoyyyaard** [comment] 2024-06-17 03:04
Or can you please provide the pointclouds of the whole room of the HM3D?

**Comment by Buzz-Beater** [comment] 2024-07-20 07:36
Hi, we just provided the preprocessing code for scenes and used RSCAN as an example, we will also provide more instructions on HM3D shortly. Thanks for the patience.

**Comment by MrZihan** [comment] 2024-08-16 20:27
Thank you for your outstanding work and for providing the preprocessing scripts for HM3D. However, I have found that the HM3D instance IDs processed by this script do not align with the SceneVerse instance IDs, which is causing me significant confusion. Could you please provide a preprocessed "tgt_id2obj_id.json"? I'm not sure if the issue is with the code or with the version of the HM3D dataset. Thanks a lot.

**Comment by MrZihan** [comment] 2024-08-16 20:28
> Hi, we just provided the preprocessing code for scenes and used RSCAN as an example, we will also provide more instructions on HM3D shortly. Thanks for the patience.

Thank you for your outstanding work and for providing the preprocessing scripts for HM3D. However, I have found that the HM3D instance IDs processed by this script do not align with the SceneVerse instance IDs, which is causing me significant confusion. Could you please provide a preprocessed "tgt_id2obj_id.json"? I'm not sure if the issue is with the code or with the version of the HM3D dataset. Thanks a lot.

**Comment by Buzz-Beater** [comment] 2024-09-02 07:06
Hi for HM3D, we have provided a ```sceneverse2hmsemantic.py``` for the id matching, you can check it out :-)

**Comment by Buzz-Beater** [comment] 2024-09-19 01:28
Closing this issue as we have already provided related files, feel free to re-open this thread if there is any issue:-)

**Closed by Buzz-Beater** 2024-09-19 01:28 UTC
